# Config strings
aperture.config:
    camera:
        title: 相機
        tooltip: 通用相機配置

        camera_duration: 預設關鍵點時長
        camera_duration_step: 時長步驟
        camera_interpolate_target: 插入以目標為基礎的幀
        camera_interpolate_target_value: 插入以目標為基礎的值
        camera_spectator: 切換到旁觀模式
        camera_step_factor: 相機路徑參數
        camera_rotate_factor: 相機傾斜參數
        camera_minema: Minema
        camera_path_default_interp: 預設插入路徑類型
        camera_command_name: 相機命令名稱
        camera_simulate_velocity: 模擬速率
        camera_first_tick_zero: 第一幀為 0
        camera_debug_ticks: Debug ticks
        camera_profile_render: 渲染相機配置
        camera_auto_save: 自動存儲配置

        gui_render_mouse: 在 GUI 中渲染出滑鼠指針

        minecrafttp_teleport: 使用 /minecraft:tp
        tp_teleport: 使用 /tp
        aspect_ratio: 縱橫比例

    outside:
        title: 分離攝像機模式
        tooltip: 屬於分離攝像機的設置項

        camera_outside: 分離攝像機模式
        camera_outside_hide_player: 隱藏玩家
        camera_outside_sky: 修復天空
        camera_outside_hide_guis: 隱藏 GUI
        camera_outside_hide_overlays: 隱藏附加層

    overlay:
        title: 相機編輯器附加層
        tooltip: 可以在相機編輯器放置一個圖片作為附加層

        camera_editor_overlay: 啟用附加層
        camera_editor_overlay_rl: 附加層的資源路徑

    smooth:
        title: 平滑相機
        tooltip: 平滑相機配置

        camera_smooth_clamp: 限制幅度

        roll_speed: 傾斜速度
        roll_friction: 傾斜摩擦力

        fov_speed: FOV 速度
        fov_friction: FOV 摩擦力

        smooth_enabled: 開啟平滑相機
        mouse_x_friction: 滑鼠 X 軸摩擦力
        mouse_y_friction: 滑鼠 Y 軸摩擦力
