# Config strings
aperture.config.comments:
    general:
        camera_duration: What is default duration of the camera fixture (in ticks)
        camera_spectator: Switch to spectator mode when starting camera playback
        camera_step_factor: Camera step factor for step keys
        camera_rotate_factor: Camera rotate factor for rotate keys
        camera_minema: Activate Minema recording on camera start and deactivate on camera stop
        camera_path_default_interp: Default interpolation method for path fixture
        camera_command_name: Allows you to rebind camera command's name (requires game reload to take effect)
        camera_simulate_velocity: Simulate player's velocity during camera playback (see legs in perspective)
        camera_debug_ticks: Write current camera playback tick to the log
        camera_first_tick_zero: When camera runner starts, start the actual playback when partial tick is exactly zero
        camera_profile_render: Render camera profile in the world?
        camera_auto_save: Save all camera profiles upon exiting the world
        minecrafttp_teleport: When start the camera playback in multiplayer, teleport you with /minecraft:tp command (For Essentials)

    outside:
        camera_outside: Whether camera should be played back from outside (allowing the player to act as a body actor)
        camera_outside_hide_player: Whether player should be hidden during playback of the camera if outside mode is enabled
        camera_outside_sky: If enabled, fixes the sky, but disables block selection (due to a bug)
        camera_outside_hide_guis: Prevent GUI screens from rendering during outside mode
        camera_outside_hide_overlays: Prevent rendering screen overlays (such as pumpkin overlay, fire when burning, water and etc.) during outside mode

    overlay:
        camera_editor_overlay: Enables camera editor overlay
        camera_editor_overlay_rl: Resource location path to the texture which will be used as overlay
        camera_editor_f1_tooltip: Show the tooltip in the bottom left corner which explains how to show back the GUI
        aspect_ratio: Aspect ratio for camera editor's letterbox feature

    flight:
        forward: Moves the camera forward
        backward: Moves the camera backward
        left: Moves the camera to the left
        right: Moves the camera to the right
        up: Ascends the camera upward
        down: Descends the camera downwards
        camera_up: Tilt the camera upward toward the sky
        camera_down: Tilt the camera downward toward the ground
        camera_left: Pan the camera to the left
        camera_right: Pan the camera to the right
        fov_minus: Narrow the Field of View
        fov_plus: Widen the Field of View
        roll_minus: Roll counter-clockwise
        roll_plus: Roll clockwise

    smooth:
        camera_smooth_clamp: Clip smooth camera's pitch between -90 and 90 degrees range?

        roll_speed: Roll acceleration speed
        roll_friction: Roll acceleration friction (how fast it slows down)

        fov_speed: FOV acceleration speed
        fov_friction: FOV acceleration friction (how fast it slows down)

        smooth_enabled: Enable smooth camera
        mouse_x_friction: Smooth mouse X friction
        mouse_y_friction: Smooth mouse Y friction
