# Config strings
aperture.config:
    camera:
        title: Camera
        tooltip: General camera options

        camera_duration_step: Duration step
        camera_duration: Default fixture duration
        camera_interpolate_target: Interpolate target fixtures
        camera_interpolate_target_value: Target interpolation value
        camera_spectator: Switch to specator
        camera_step_factor: Camera step factor
        camera_rotate_factor: Camera rotate factor
        camera_minema: Minema
        camera_path_default_interp: Default path interpolation
        camera_command_name: Camera command name
        camera_simulate_velocity: Velocity simulation
        camera_first_tick_zero: First tick zero
        camera_debug_ticks: Debug ticks
        camera_profile_render: Render camera profile

        gui_render_mouse: Render mouse cursor in GUIs

        minecrafttp_teleport: Use /minecraft:tp
        tp_teleport: Use /tp
        aspect_ratio: Aspect ratio

    outside: 
        title: Outside mode
        tooltip: Config options related to outside mode
        
        camera_outside: Outside mode
        camera_outside_hide_player: Hide player
        camera_outside_sky: Fix sky
        camera_outside_hide_guis: Hide GUIs
        camera_outside_hide_overlays: Hide overlays

    smooth:
        title: Smooth camera
        tooltip: Smooth camera options

        camera_smooth_clamp: Limit pitch

        roll_speed: Roll speed
        roll_friction: Roll friction

        fov_speed: FOV speed
        fov_friction: FOV friction

        smooth_enabled: Smooth camera enabled
        mouse_x_friction: Mouse X friction
        mouse_y_friction: Mouse Y friction
