# Config strings
aperture.config:
    camera:
        title: 相机
        tooltip: 通用相机配置

        camera_duration: 默认关键点时长
        camera_duration_step: 时长步骤
        camera_interpolate_target: 插入以目标为基础的帧
        camera_interpolate_target_value: 插入以目标为基础的值
        camera_spectator: 切换到旁观模式
        camera_step_factor: 相机路径参数
        camera_rotate_factor: 相机倾斜参数
        camera_minema: Minema
        camera_path_default_interp: 默认插入路径类型
        camera_command_name: 相机命令名称
        camera_simulate_velocity: 模拟速率
        camera_first_tick_zero: 第一帧为 0
        camera_debug_ticks: Debug ticks
        camera_profile_render: 渲染相机配置
        camera_auto_save: 自动保存配置

        gui_render_mouse: 在 GUI 中渲染出鼠标指针

        minecrafttp_teleport: 使用 /minecraft:tp
        tp_teleport: 使用 /tp
        aspect_ratio: 纵横比

    outside:
        title: 分离摄像机模式
        tooltip: 属于分离摄像机的设置项

        camera_outside: 分离摄像机模式
        camera_outside_hide_player: 隐藏玩家
        camera_outside_sky: 修复天空
        camera_outside_hide_guis: 隐藏 GUI
        camera_outside_hide_overlays: 隐藏附加层

    overlay:
        title: 相机编辑器附加层
        tooltip: 可以在相机编辑器放置一个图片作为附加层

        camera_editor_overlay: 启用附加层
        camera_editor_overlay_rl: 附加层的资源路径
        camera_editor_f1_tooltip: F1 隐藏提示

    smooth:
        title: 平滑相机
        tooltip: 平滑相机配置

        camera_smooth_clamp: 限制幅度

        roll_speed: 倾斜速度
        roll_friction: 倾斜摩擦力

        fov_speed: FOV 速度
        fov_friction: FOV 摩擦力

        smooth_enabled: 开启平滑相机
        mouse_x_friction: 鼠标 X 轴摩擦力
        mouse_y_friction: 鼠标 Y 轴摩擦力
