# Config strings
aperture.config:
    camera:
        title: 相机
        tooltip: 通用相机配置
        
        camera_duration: 默认关键点时长
        camera_duration_step: 时长步骤
        camera_interpolate_target: 插入以目标为基础的帧
        camera_interpolate_target_value: 插入以目标为基础的值
        camera_spectator: 切换到旁观模式
        camera_step_factor: 相机路径参数
        camera_rotate_factor: 相机倾斜参数
        camera_minema: Minema
        camera_smooth_clamp: 修剪相机俯仰程度
        camera_path_default_interp: 默认插入路径类型
        camera_command_name: 相机命令名称
        camera_simulate_velocity: 模拟速率
        
    smooth:
        title: 平滑相机
        tooltip: 平滑相机配置
        
            roll_speed: 倾斜速度
            roll_friction: 倾斜摩擦力

            fov_speed: FOV 速度
            fov_friction: FOV 摩擦力

            smooth_enabled: 开启平滑相机
            mouse_x_friction: 鼠标X轴摩擦力
            mouse_y_friction: 鼠标Y轴摩擦力
