# Config strings
aperture.config.comments:
    camera:
        camera_duration_step: 当使用快捷键改变关键点时长时，一次会增加/减少多少？（tick）
        camera_duration: 相机关键点的默认时长有多久？（tick）
        camera_interpolate_target: 插入目标为基础（follow 和 look）的相机关键点的结果
        camera_interpolate_target_value: 插入目标为基础相机关键点的值
        camera_spectator: 当开始播放相机回放时切换到旁观模式？
        camera_step_factor: 为路径帧提供的相机路径参数
        camera_rotate_factor: 按键相机一次倾斜的大小
        camera_minema: 为倾斜帧提供的相机倾斜参数
        camera_path_default_interp: 插入路径时，路径的默认类型
        camera_command_name: 允许你重新绑定相机命令的名字（需要重启游戏来生效）
        camera_simulate_velocity: 在回放时模拟玩家走动摇摆（从腿的角度）
        camera_debug_ticks: 将目前播放的 tick 时间写入日志文件
        camera_first_tick_zero: 当相机播放时将当前帧归零
        camera_profile_render: 在世界中渲染出相机配置？
        gui_render_mouse: 在打开 GUI 的时候渲染出鼠标的材质
        minecrafttp_teleport: 当在多人游戏时开始相机回放，使用 /minecraft:tp 来瞬移（针对于安装了 Essentials 插件的服务器）
        tp_teleport: 当在多人游戏时开始相机回放，使用 /tp 来瞬移（针对于原版和 Forge 等服务器）
        aspect_ratio: 用于设置画面黑边的纵横比

        outside:
            camera_outside: 摄像机是否应该与玩家分离开来播放（允许玩家作为一个真实演员）？
            camera_outside_hide_player: 在开启分离摄像机模式时，播放器是否应该在播放的时候隐藏？
            camera_outside_sky: 如果打开，会修复天空，但会关闭区块选区（因为有一个 bug）
            camera_outside_hide_guis: 防止在分离摄像机模式中渲染 GUI
            camera_outside_hide_overlays: 防止在分离摄像机模式中渲染屏幕附加层（比如南瓜灯的光，正在燃烧的火，水等等）

    smooth:
        camera_smooth_clamp: 在 －90 和 90 度之间，修剪平滑相机的俯仰程度？嗡!嗡!嗡!

        roll_speed: 倾斜加速速度
        roll_friction: 倾斜加速摩擦力（慢下来有多快）

        fov_speed: FOV 加速速度
        fov_friction: FOV 加速摩擦力（慢下来有多快）

        smooth_enabled: 开启平滑相机。嗡!嗡!嗡!
        mouse_x_friction: 鼠标平滑 X 轴摩擦力
        mouse_y_friction: 鼠标平滑 Y 轴摩擦力
