# Config strings
aperture.config.comments:
    camera:
        camera_duration_step: Значение продолжительности точки по умолчанию (в тиках)
        camera_duration: Значение продолжительности камеры (в тиках)
        camera_interpolate_target: Интерполировать целенаправленные клипы камеры (следовать и следить)
        camera_interpolate_target_value: Значение интерполяции для интерполяции клипа целенаправленной камеры
        camera_spectator: Переключение в режим наблюдателя во время начала воспроизведения камеры
        camera_step_factor: Кнопки для движения камеры
        camera_rotate_factor: Кнопки для вращения камеры
        camera_minema: Активировать Минему в начале движения камеры и деактивировать в конце
        camera_path_default_interp: Метод интерполяции для траектории клипов по умолчанию
        camera_command_name: Позволяет вам переназначить команду камеры (для применения необходим перезапуск игры)
        camera_simulate_velocity: Симулировать скорость игрока во время воспроизвдедения камеры (видеть ноги в перспективе)
        camera_debug_ticks: Записать тики текущего воспроизведения камеры в лог?
        camera_first_tick_zero: Когда начинается воспроизведение камеры, прогружать запись если частичный тик равняется ровно нулю?
        camera_profile_render: Отображать профиль камеры в мире?
        camera_auto_save: Сохранить все профили во время выхода из мира?
        gui_render_mouse: Необходимо ли отображать курсор мыши во время взаимодействия с интерфейсом?
        minecrafttp_teleport: Необходимо ли телепортировать вас командой /minecraft:tp (для Essentials), когда начинется воспроизведение камеры в мультиплеере
        tp_teleport: Необходимо ли телепортировать вас командой /tp (Для Ваниллы и Forge), когда начинется воспроизведение камеры в мультиплеере
        aspect_ratio: Пропорции для каше редактора камеры

    outside:
        camera_outside: Должна ли быть камера воспроизведена снаружи (позволяя игроку быть актером)
        camera_outside_hide_player: Должен ли быть игрок спрятан во время воспроизведния записи если включен внешний режим?
        camera_outside_sky: Если включено, то исправляет небо, но отключает выбор блока (из-за бага)
        camera_outside_hide_guis: Предотвращать отображение интерфейса во время использования внешнего режима?
        camera_outside_hide_overlays: Предотвращать отображение оверлеев (такие как оверлей надетой тыквы, оверлей огня когда горишь, воды и т.д.) во время использования внешнего режима?
    
    overlay:
        camera_editor_overlay: Включает оверлей редактора камеры
        camera_editor_overlay_rl: Путь к текстуре, которая будет использована в качестве оверлея

    smooth:
        camera_smooth_clamp: Ограничить тангаж камеры до -90 и 90 градусов? ТЫЦ ТЫЦ ТЫЦ

        roll_speed: Скорость ускорения крена
        roll_friction: Ослабление скорости крена (насколько быстро он замедляется)

        fov_speed: Скорость ускорения поля зрения
        fov_friction: Ослабление скорости поля зрения (насколько быстро оно замедляется)

        smooth_enabled: Включить гладкое движение камеры. ТЫЦ ТЫЦ ТЫЦ
        mouse_x_friction: Ослаление гладоксти по оси Х
        mouse_y_friction: Ослаление гладоксти по оси Y
